Plot optimization
fund3/sentiment-dashboard pull request #5
Opened 2019-02-25 22:25 UTC by gdiazc

The Elasticsearch instance now stores pre-computed "mean hourly sentiment ticks" in a separate index. This pull requests migrates the dashboard over to this pre-computed data so it doesn't have to be calculated on the fly.

2019-02-26 00:00 UTC, dev1-fund3 requested changes

2019-02-26 00:00 UTC, dev1-fund3 commented on app.py
> +def get_mean_sentiments():
add docstring comments for what this method does

2019-02-26 00:00 UTC, dev1-fund3 commented on es_client.py
> +    :param client: Elasticsearch client object.
add docstring for max_ticks

2019-02-26 00:00 UTC, dev1-fund3 commented on es_client.py
> +    ticks = []
```suggestion
    return [
        {
            'timestamp': hit.to_dict().get('timestamp', None),
            'value': hit.to_dict().get('value', None)
        } for hit in search
    ]
```

2019-02-26 00:00 UTC, dev1-fund3 commented on es_client.py
> +    ticks = []
Use list compression and fewer local vars for speed up.

2019-02-26 00:00 UTC, dev1-fund3 commented on plotting.py
> +    p.x_range = bokeh.models.Range1d(now - datetime.timedelta(days=3), now + datetime.timedelta(hours=6))
add a low priority TODO to make the range able to be input by user via dropdown menu.

2019-02-26 00:00 UTC, dev1-fund3 commented on static/bitcoin_sentiments.js
> +            // Get sentiment ticks quicker:
```suggestion
            // Get precomputed sentiment ticks:
```

2019-03-12 17:08 UTC, gdiazc commented on app.py
> +def get_mean_sentiments():
Fixed in [3fd135b](https://github.com/fund3/sentiment-dashboard/pull/5/commits/3fd135bb0e6622d2d74fb1c882b41c9378f306c3)

2019-03-12 17:09 UTC, gdiazc commented on es_client.py
> +    :param client: Elasticsearch client object.
Fixed in [3fd135b](https://github.com/fund3/sentiment-dashboard/pull/5/commits/3fd135bb0e6622d2d74fb1c882b41c9378f306c3)

2019-03-12 17:09 UTC, gdiazc commented on es_client.py
> +    ticks = []
Fixed in [3fd135b](https://github.com/fund3/sentiment-dashboard/pull/5/commits/3fd135bb0e6622d2d74fb1c882b41c9378f306c3)

2019-03-12 17:09 UTC, gdiazc commented on plotting.py
> +    p.x_range = bokeh.models.Range1d(now - datetime.timedelta(days=3), now + datetime.timedelta(hours=6))
Fixed in [3fd135b](https://github.com/fund3/sentiment-dashboard/pull/5/commits/3fd135bb0e6622d2d74fb1c882b41c9378f306c3)

2019-03-12 17:09 UTC, gdiazc commented on static/bitcoin_sentiments.js
> +            // Get sentiment ticks quicker:
Fixed in [3fd135b](https://github.com/fund3/sentiment-dashboard/pull/5/commits/3fd135bb0e6622d2d74fb1c882b41c9378f306c3)

2019-03-12 17:40 UTC, dev1-fund3 approved these changes

2019-03-12 18:39 UTC, merged